# Read the Docs configuration file
# modified April 2022 by DLW
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# setup mpi-sppy
python:
   version: "3.8"
   install:
      - method: setuptools
        path: .

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/src/conf.py
